<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403103004 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, matricule VARCHAR(20) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, centre VARCHAR(100) DEFAULT NULL, date_naissance TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, actif BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_268B9C9D12B2DC9C ON agent (matricule)');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, centre VARCHAR(100) DEFAULT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE commentaire_signalement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, signalement_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_19B5E00665C5E57E ON commentaire_signalement (signalement_id)');
        $this->addSql('CREATE INDEX IDX_19B5E006A76ED395 ON commentaire_signalement (user_id)');
        $this->addSql('CREATE TABLE courrier_draft (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, statut VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, signalement_id INT NOT NULL, validated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8E2517A465C5E57E ON courrier_draft (signalement_id)');
        $this->addSql('CREATE INDEX IDX_8E2517A4C69DE5E5 ON courrier_draft (validated_by_id)');
        $this->addSql('CREATE TABLE historique_statut (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ancien_statut VARCHAR(20) DEFAULT NULL, nouveau_statut VARCHAR(20) NOT NULL, commentaire TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, signalement_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C2650E365C5E57E ON historique_statut (signalement_id)');
        $this->addSql('CREATE INDEX IDX_2C2650E3A76ED395 ON historique_statut (user_id)');
        $this->addSql('CREATE TABLE signalement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, canal VARCHAR(20) NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, date_fait TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, gravite VARCHAR(10) DEFAULT NULL, statut VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, agent_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F4B551143414710B ON signalement (agent_id)');
        $this->addSql('CREATE INDEX IDX_F4B55114B03A8386 ON signalement (created_by_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE commentaire_signalement ADD CONSTRAINT FK_19B5E00665C5E57E FOREIGN KEY (signalement_id) REFERENCES signalement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commentaire_signalement ADD CONSTRAINT FK_19B5E006A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE courrier_draft ADD CONSTRAINT FK_8E2517A465C5E57E FOREIGN KEY (signalement_id) REFERENCES signalement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE courrier_draft ADD CONSTRAINT FK_8E2517A4C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historique_statut ADD CONSTRAINT FK_2C2650E365C5E57E FOREIGN KEY (signalement_id) REFERENCES signalement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historique_statut ADD CONSTRAINT FK_2C2650E3A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE signalement ADD CONSTRAINT FK_F4B551143414710B FOREIGN KEY (agent_id) REFERENCES agent (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE signalement ADD CONSTRAINT FK_F4B55114B03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commentaire_signalement DROP CONSTRAINT FK_19B5E00665C5E57E');
        $this->addSql('ALTER TABLE commentaire_signalement DROP CONSTRAINT FK_19B5E006A76ED395');
        $this->addSql('ALTER TABLE courrier_draft DROP CONSTRAINT FK_8E2517A465C5E57E');
        $this->addSql('ALTER TABLE courrier_draft DROP CONSTRAINT FK_8E2517A4C69DE5E5');
        $this->addSql('ALTER TABLE historique_statut DROP CONSTRAINT FK_2C2650E365C5E57E');
        $this->addSql('ALTER TABLE historique_statut DROP CONSTRAINT FK_2C2650E3A76ED395');
        $this->addSql('ALTER TABLE signalement DROP CONSTRAINT FK_F4B551143414710B');
        $this->addSql('ALTER TABLE signalement DROP CONSTRAINT FK_F4B55114B03A8386');
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE commentaire_signalement');
        $this->addSql('DROP TABLE courrier_draft');
        $this->addSql('DROP TABLE historique_statut');
        $this->addSql('DROP TABLE signalement');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
