<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403110211 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE piece_jointe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, signalement_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB5111D465C5E57E ON piece_jointe (signalement_id)');
        $this->addSql('CREATE INDEX IDX_AB5111D4A2B28FE8 ON piece_jointe (uploaded_by_id)');
        $this->addSql('ALTER TABLE piece_jointe ADD CONSTRAINT FK_AB5111D465C5E57E FOREIGN KEY (signalement_id) REFERENCES signalement (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE piece_jointe ADD CONSTRAINT FK_AB5111D4A2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE signalement DROP CONSTRAINT fk_f4b551143414710b');
        $this->addSql('ALTER TABLE signalement ADD agent_description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE signalement ALTER agent_id DROP NOT NULL');
        $this->addSql('ALTER TABLE signalement ADD CONSTRAINT FK_F4B551143414710B FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE piece_jointe DROP CONSTRAINT FK_AB5111D465C5E57E');
        $this->addSql('ALTER TABLE piece_jointe DROP CONSTRAINT FK_AB5111D4A2B28FE8');
        $this->addSql('DROP TABLE piece_jointe');
        $this->addSql('ALTER TABLE signalement DROP CONSTRAINT FK_F4B551143414710B');
        $this->addSql('ALTER TABLE signalement DROP agent_description');
        $this->addSql('ALTER TABLE signalement ALTER agent_id SET NOT NULL');
        $this->addSql('ALTER TABLE signalement ADD CONSTRAINT fk_f4b551143414710b FOREIGN KEY (agent_id) REFERENCES agent (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
