<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260403170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute la configuration des fournisseurs IA';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ai_provider_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, provider_type VARCHAR(40) NOT NULL, vendor_label VARCHAR(120) DEFAULT NULL, api_base_url VARCHAR(255) DEFAULT NULL, api_key_encrypted TEXT DEFAULT NULL, model VARCHAR(160) NOT NULL, system_prompt TEXT DEFAULT NULL, context_template TEXT DEFAULT NULL, active BOOLEAN NOT NULL, is_default BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE ai_provider_config');
    }
}
