<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260403213000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute audit log et paramètres avancés de configuration IA';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(80) NOT NULL, actor_email VARCHAR(120) DEFAULT NULL, actor_label VARCHAR(120) NOT NULL, subject_type VARCHAR(80) DEFAULT NULL, subject_id INT DEFAULT NULL, summary TEXT NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE ai_provider_config ADD api_path VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE ai_provider_config ADD extra_headers TEXT DEFAULT NULL');
        $this->addSql("ALTER TABLE ai_provider_config ADD temperature DOUBLE PRECISION DEFAULT '0.2' NOT NULL");
        $this->addSql("ALTER TABLE ai_provider_config ADD timeout_seconds INT DEFAULT 20 NOT NULL");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('ALTER TABLE ai_provider_config DROP api_path');
        $this->addSql('ALTER TABLE ai_provider_config DROP extra_headers');
        $this->addSql('ALTER TABLE ai_provider_config DROP temperature');
        $this->addSql('ALTER TABLE ai_provider_config DROP timeout_seconds');
    }
}
